language: php
php:
    - 5.5
before_install:
    - wget https://phar.phpunit.de/phpunit.phar
    - chmod +x phpunit.phar
    - mv phpunit.phar /usr/local/bin/phpunit
script:
    - php *test.php
notifications:
    email: false
